#!/usr/bin/env bash
# Regenerate docker/requirements-<name>.txt (hash-pinned) from
# docker/requirements-<name>.in.
#
#   docker/lock_requirements.sh test
#
# Run it with the image's interpreter (Python 3.12 on linux x86_64, e.g. on
# Ubuntu 24.04 or inside the test image): pip resolves for the running
# interpreter and platform and records one sha256 per file it would install.
# pip-compile is not used because it cannot hash torch's "+cpu" local
# versions across two indexes.
set -euo pipefail

name="${1:?usage: lock_requirements.sh <name>}"
here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
in="${here}/requirements-${name}.in"
out="${here}/requirements-${name}.txt"
[[ -f "${in}" ]] || { echo "${in} not found" >&2; exit 2; }
py="${PYTHON:-python3}"
"${py}" -c 'import sys; assert sys.version_info[:2] == (3, 12), sys.version' \
  || { echo "run with Python 3.12 (set PYTHON=...)" >&2; exit 2; }

work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT
"${py}" -m venv "${work}/venv"
"${work}/venv/bin/python" -m pip install --quiet --upgrade pip
"${work}/venv/bin/python" -m pip install --quiet --dry-run --ignore-installed \
  --retries 5 --timeout 120 --report "${work}/report.json" -r "${in}"

{
  echo "# Generated by docker/lock_requirements.sh from requirements-${name}.in."
  echo "# Python 3.12, linux x86_64 (the test image). Do not edit by hand."
  grep -E '^--(index-url|extra-index-url)' "${in}" || true
  "${work}/venv/bin/python" - "${work}/report.json" <<'PY'
import json
import sys

report = json.load(open(sys.argv[1]))
rows = []
for item in report["install"]:
    meta = item["metadata"]
    info = item["download_info"].get("archive_info", {})
    sha = info.get("hashes", {}).get("sha256") or info.get("hash", "").removeprefix("sha256=")
    if not sha:
        sys.exit(f"no sha256 for {meta['name']}")
    rows.append((item.get("requested", False), meta["name"].lower().replace("_", "-"), meta["version"], sha))
# Requested packages first, then dependencies alphabetically.
for _, name, version, sha in sorted(rows, key=lambda r: (not r[0], r[1])):
    print(f"{name}=={version} --hash=sha256:{sha}")
PY
} >"${out}"
echo "wrote ${out}"
